
DELETE FROM `rex_xform_table` where `table_name`='rex_com_user';
INSERT INTO `rex_xform_table` (`status`, `table_name`, `name`, `description`, `list_amount`, `prio`, `search`, `hidden`, `export`, `import`) VALUES (1, 'rex_com_user', 'community user', 'communityuser', 100, 100, 1, 0, 1, 1);

DELETE FROM `rex_xform_field` where `table_name`='rex_com_user';
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 10, 'value', 'text', 'login', 'translate:login', '', '0', '', '', '', '', '', 0, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 20, 'validate', 'empty', 'login', 'translate:com_please_enter_login', '', '', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 30, 'validate', 'unique', 'login', 'translate:com_this_login_exists_already', 'rex_com_user', '', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 40, 'value', 'text', 'password', 'translate:password', '', '0', '', '', '', '', '', 1, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 50, 'validate', 'empty', 'password', 'translate:com_please_enter_password', '', '', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 60, 'value', 'text', 'email', 'translate:email', '', '0', '', '', '', '', '', 0, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 70, 'validate', 'empty', 'email', 'translate:com_please_enter_email', '', '', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 80, 'validate', 'email', 'email', 'translate:com_please_enter_email', '', '', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 90, 'validate', 'unique', 'email', 'translate:com_this_email_exists_already', '', '', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 100, 'value', 'select', 'status', 'translate:status', 'translate:com_account_requested=0,translate:com_account_active=1,translate:com_account_inactive=-1', '0', '-1', '0', '', '', '', 0, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 110, 'value', 'text', 'firstname', 'translate:firstname', '', '0', '', '', '', '', '', 0, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 120, 'value', 'text', 'name', 'translate:name', '', '0', '', '', '', '', '', 0, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 130, 'value', 'text', 'activation_key', 'translate:activation_key', '', '0', '', '', '', '', '', 1, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES ('rex_com_user', 140, 'value', 'text', 'session_key', 'translate:session_key', '', '0', '', '', '', '', '', 1, 1);
