package: ycom
version: '2.1'
author: Yakamara Media GmbH & Co. KG, concedra GmbH
supportpage: www.redaxo.org/de/forum

page:
    title: 'translate:ycom_navi_title'
    perm: ycom[]
    block: ycom
    icon: rex-icon fa-group
    subpages:
        main:
           title: 'translate:ycom_main_title'
           perm: 'admin[]'
           subpages:
                info: { title: 'translate:ycom_info' }
                manual: { title: 'translate:ycom_manual' }

requires:
    packages:
        yform: '^2.3'
        phpmailer: '^2.0.1'
    redaxo: '^5.5.0'

system_plugins:
    - auth
    - group