package: ycom
version: '4.0.6'
author: Yakamara Media GmbH & Co. KG, concedra GmbH
supportpage: https://github.com/yakamara/redaxo_ycom/

page:
    title: 'translate:ycom_navi_title'
    perm: ycom[]
    block: ycom
    icon: rex-icon fa-group
    subpages:
        docs:
            title: 'translate:docs'
            perm: admin[]
            pjax: false
            itemclass: pull-right
            icon: rex-icon fa-info-circle

requires:
    packages:
        yform: '>=3.3.1'
        yrewrite: '>=2.6'
        phpmailer: '>=2.2'
    redaxo: '^5.12.0'

system_plugins:
    - auth
    - group
