package: ycom
version: '4.2.1'
author: Yakamara Media GmbH & Co. KG
supportpage: https://github.com/yakamara/redaxo_ycom/

page:
    title: 'translate:ycom_navi_title'
    perm: admin[]
    block: ycom
    icon: rex-icon fa-group
    subpages:
        docs:
            title: 'translate:ycom_docs'
            perm: admin[]
            pjax: false
            itemclass: pull-right
            icon: rex-icon fa-info-circle

requires:
    php: '>=8.1'
    packages:
        yform: '^4.1.1'
        yrewrite: '>=2.6'
    redaxo: '^5.15.0'

system_plugins:
    - auth
    - group

default_config:
    auto_model_class: true
