package: ycom
version: '4.4.1'
author: Yakamara Media GmbH & Co. KG
supportpage: https://github.com/yakamara/redaxo_ycom/

page:
    title: 'translate:ycom_navi_title'
    perm: admin[]
    block: ycom
    icon: rex-icon fa-group
    subpages:
        docs:
            title: 'translate:ycom_docs'
            perm: admin[]
            pjax: false
            itemClass: pull-right
            icon: rex-icon fa-info-circle
            href: ?page=ycom/docs

requires:
    php: '>=8.2'
    packages:
        yform: '>=3.2,<6.0.0-dev'
        yrewrite: '>=2.6'
    redaxo: '^5.17.0'

installer_ignore:
    - .tools
    - .github

system_plugins:
    - auth
    - group
