

DELETE FROM `rex_xform_table` where `table_name`='rex_com_comment';
INSERT INTO `rex_xform_table` (`status`, `table_name`, `name`, `description`, `list_amount`, `prio`, `search`, `hidden`, `export`, `import`) VALUES(1, 'rex_com_comment', 'translate:com_comment', '', 50, 120, 1, 0, 0, 0);

DELETE FROM `rex_xform_field` where `table_name`='rex_com_comment';

INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 90, 'value', 'text', 'ckey', 'translate:com_comment_ckey', '', '', '', '', '', '', '', 0, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 190, 'value', 'index', 'ukey', 'email,user_id,name,comment,ckey,www', '', 'sha1', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 110, 'value', 'checkbox', 'info_email', 'translate:com_comment_infomail', '', '0', '', '', '', '', '', 1, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 80, 'value', 'checkbox', 'status', 'translate:status', '', '0', '', '', '', '', '', 1, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 70, 'value', 'datestamp', 'update_datetime', 'mysql', '', '0', '', '', '', '', '', 0, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 60, 'value', 'datestamp', 'create_datetime', 'mysql', '', '1', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 50, 'value', 'be_manager_relation', 'user_id', 'translate:com_user', 'rex_com_user', 'name', '0', '1', '', '', '', 0, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 40, 'value', 'text', 'name', 'translate:name', '', '', '', '', '', '', '', 0, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 30, 'value', 'text', 'email', 'translate:email', '', '', '', '', '', '', '', 0, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 35, 'validate', 'type', 'email', 'email', 'translate:com_comment_enteremail', '0', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 20, 'validate', 'empty', 'comment', 'translate:com_comment_enter_comment', '', '', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 10, 'value', 'textarea', 'comment', 'translate:com_comment_name', '', '', '', '', '', '', '', 1, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 45, 'validate', 'empty', 'name', 'translate:com_comment_enter_name', '', '', '', '', '', '', '', 1, 0);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 55, 'value', 'text', 'www', 'translate:com_comment_www', '', '', '', '', '', '', '', 1, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 130, 'value', 'be_manager_relation', 'reply_to', 'translate:com_comment_replyto', 'rex_com_comment', 'ckey', '0', '1', '', '', '', 1, 1);
INSERT INTO `rex_xform_field` (`table_name`, `prio`, `type_id`, `type_name`, `f1`, `f2`, `f3`, `f4`, `f5`, `f6`, `f7`, `f8`, `f9`, `list_hidden`, `search`) VALUES('rex_com_comment', 200, 'validate', 'unique', 'ukey', 'translate:com_comment_enter_exists', '', '', '', '', '', '', '', 1, 0);
