password|password|Neues Passwort:
password|password_2|Passwort wiederholen:||no_db
validate|empty|password|Bitte geben Sie ein Passwort ein.
validate|compare|password|password_2|Bitte geben Sie zweimal das gleiche Passwort ein
action|showtext||<div><ul><li>Ihre Daten wurden aktualisiert. Das neue Passwort ist ab sofort aktiv.</li></ul></div>||1
com_auth_password_hash|password|password|
action|com_auth_db